# Dockerfile

# CDSW base image
FROM docker.repository.cloudera.com/cdsw/engine:8
RUN apt-get update

# tesseract
RUN sudo apt install tesseract-ocr
RUN sudo apt-get install tesseract-ocr-all

# imagemagick
RUN sudo apt install imagemagick
